version: '3.3'

services:
  weather-server:
    build: ./Server/
    tty: true
    command: python3 app.py
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    restart: always
    networks:
            - my_net
    depends_on:
      - postgres-db
    volumes:
      - type: bind
        source: ./Server/app
        target: /app/
  postgres-db:
    image: postgres:15.1-bullseye
    networks:
            - my_net
    volumes:
      - postgres-dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

networks:
        my_net:
                driver: bridge

volumes:
  postgres-dev:
